__title__ = 'spacybert'
__version__ = '1.0.0'
__summary__ = 'spaCy pipeline component for adding Bert embedding meta data to Doc, Token and Span objects.'
__uri__ = 'https://github.com/surajiyer/spacybert'
__author__ = 'Suraj Iyer'
__email__ = 'me@surajiyer.com'
__license__ = 'MIT'